// Generated by gencpp from file ai_msgs/Det.msg
// DO NOT EDIT!


#ifndef AI_MSGS_MESSAGE_DET_H
#define AI_MSGS_MESSAGE_DET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ai_msgs
{
template <class ContainerAllocator>
struct Det_
{
  typedef Det_<ContainerAllocator> Type;

  Det_()
    : x1(0)
    , y1(0)
    , x2(0)
    , y2(0)
    , conf(0.0)
    , cls_name()
    , cls_id(0)
    , obj_id(0)  {
    }
  Det_(const ContainerAllocator& _alloc)
    : x1(0)
    , y1(0)
    , x2(0)
    , y2(0)
    , conf(0.0)
    , cls_name(_alloc)
    , cls_id(0)
    , obj_id(0)  {
  (void)_alloc;
    }



   typedef uint16_t _x1_type;
  _x1_type x1;

   typedef uint16_t _y1_type;
  _y1_type y1;

   typedef uint16_t _x2_type;
  _x2_type x2;

   typedef uint16_t _y2_type;
  _y2_type y2;

   typedef float _conf_type;
  _conf_type conf;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cls_name_type;
  _cls_name_type cls_name;

   typedef uint16_t _cls_id_type;
  _cls_id_type cls_id;

   typedef uint16_t _obj_id_type;
  _obj_id_type obj_id;





  typedef boost::shared_ptr< ::ai_msgs::Det_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ai_msgs::Det_<ContainerAllocator> const> ConstPtr;

}; // struct Det_

typedef ::ai_msgs::Det_<std::allocator<void> > Det;

typedef boost::shared_ptr< ::ai_msgs::Det > DetPtr;
typedef boost::shared_ptr< ::ai_msgs::Det const> DetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ai_msgs::Det_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ai_msgs::Det_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ai_msgs::Det_<ContainerAllocator1> & lhs, const ::ai_msgs::Det_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2 &&
    lhs.conf == rhs.conf &&
    lhs.cls_name == rhs.cls_name &&
    lhs.cls_id == rhs.cls_id &&
    lhs.obj_id == rhs.obj_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ai_msgs::Det_<ContainerAllocator1> & lhs, const ::ai_msgs::Det_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ai_msgs::Det_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ai_msgs::Det_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ai_msgs::Det_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ai_msgs::Det_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ai_msgs::Det_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ai_msgs::Det_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ai_msgs::Det_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d7de293104c297a8e98d544eb51f85";
  }

  static const char* value(const ::ai_msgs::Det_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d7de293104c297ULL;
  static const uint64_t static_value2 = 0xa8e98d544eb51f85ULL;
};

template<class ContainerAllocator>
struct DataType< ::ai_msgs::Det_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ai_msgs/Det";
  }

  static const char* value(const ::ai_msgs::Det_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ai_msgs::Det_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 x1\n"
"uint16 y1\n"
"uint16 x2\n"
"uint16 y2\n"
"float32 conf\n"
"string cls_name\n"
"uint16 cls_id\n"
"uint16 obj_id\n"
"\n"
;
  }

  static const char* value(const ::ai_msgs::Det_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ai_msgs::Det_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.conf);
      stream.next(m.cls_name);
      stream.next(m.cls_id);
      stream.next(m.obj_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Det_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ai_msgs::Det_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ai_msgs::Det_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "conf: ";
    Printer<float>::stream(s, indent + "  ", v.conf);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cls_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cls_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cls_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.cls_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "obj_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.obj_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AI_MSGS_MESSAGE_DET_H
