// Generated by gencpp from file ai_msgs/Dets.msg
// DO NOT EDIT!


#ifndef AI_MSGS_MESSAGE_DETS_H
#define AI_MSGS_MESSAGE_DETS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ai_msgs/Det.h>

namespace ai_msgs
{
template <class ContainerAllocator>
struct Dets_
{
  typedef Dets_<ContainerAllocator> Type;

  Dets_()
    : header()
    , dets()  {
    }
  Dets_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dets(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ai_msgs::Det_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ai_msgs::Det_<ContainerAllocator> >> _dets_type;
  _dets_type dets;





  typedef boost::shared_ptr< ::ai_msgs::Dets_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ai_msgs::Dets_<ContainerAllocator> const> ConstPtr;

}; // struct Dets_

typedef ::ai_msgs::Dets_<std::allocator<void> > Dets;

typedef boost::shared_ptr< ::ai_msgs::Dets > DetsPtr;
typedef boost::shared_ptr< ::ai_msgs::Dets const> DetsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ai_msgs::Dets_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ai_msgs::Dets_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ai_msgs::Dets_<ContainerAllocator1> & lhs, const ::ai_msgs::Dets_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.dets == rhs.dets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ai_msgs::Dets_<ContainerAllocator1> & lhs, const ::ai_msgs::Dets_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ai_msgs::Dets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ai_msgs::Dets_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ai_msgs::Dets_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ai_msgs::Dets_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ai_msgs::Dets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ai_msgs::Dets_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ai_msgs::Dets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1999d0746b539c8853b8929d95aeea9";
  }

  static const char* value(const ::ai_msgs::Dets_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1999d0746b539c8ULL;
  static const uint64_t static_value2 = 0x853b8929d95aeea9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ai_msgs::Dets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ai_msgs/Dets";
  }

  static const char* value(const ::ai_msgs::Dets_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ai_msgs::Dets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Det[] dets\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ai_msgs/Det\n"
"uint16 x1\n"
"uint16 y1\n"
"uint16 x2\n"
"uint16 y2\n"
"float32 conf\n"
"string cls_name\n"
"uint16 cls_id\n"
"uint16 obj_id\n"
"\n"
;
  }

  static const char* value(const ::ai_msgs::Dets_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ai_msgs::Dets_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Dets_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ai_msgs::Dets_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ai_msgs::Dets_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dets: ";
    if (v.dets.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.dets.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::ai_msgs::Det_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.dets[i]);
    }
    if (v.dets.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // AI_MSGS_MESSAGE_DETS_H
