# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ai_msgs/Det.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Det(genpy.Message):
  _md5sum = "36d7de293104c297a8e98d544eb51f85"
  _type = "ai_msgs/Det"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 x1
uint16 y1
uint16 x2
uint16 y2
float32 conf
string cls_name
uint16 cls_id
uint16 obj_id

"""
  __slots__ = ['x1','y1','x2','y2','conf','cls_name','cls_id','obj_id']
  _slot_types = ['uint16','uint16','uint16','uint16','float32','string','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x1,y1,x2,y2,conf,cls_name,cls_id,obj_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Det, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x1 is None:
        self.x1 = 0
      if self.y1 is None:
        self.y1 = 0
      if self.x2 is None:
        self.x2 = 0
      if self.y2 is None:
        self.y2 = 0
      if self.conf is None:
        self.conf = 0.
      if self.cls_name is None:
        self.cls_name = ''
      if self.cls_id is None:
        self.cls_id = 0
      if self.obj_id is None:
        self.obj_id = 0
    else:
      self.x1 = 0
      self.y1 = 0
      self.x2 = 0
      self.y2 = 0
      self.conf = 0.
      self.cls_name = ''
      self.cls_id = 0
      self.obj_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4Hf().pack(_x.x1, _x.y1, _x.x2, _x.y2, _x.conf))
      _x = self.cls_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2H().pack(_x.cls_id, _x.obj_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.x1, _x.y1, _x.x2, _x.y2, _x.conf,) = _get_struct_4Hf().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cls_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cls_name = str[start:end]
      _x = self
      start = end
      end += 4
      (_x.cls_id, _x.obj_id,) = _get_struct_2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4Hf().pack(_x.x1, _x.y1, _x.x2, _x.y2, _x.conf))
      _x = self.cls_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2H().pack(_x.cls_id, _x.obj_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.x1, _x.y1, _x.x2, _x.y2, _x.conf,) = _get_struct_4Hf().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cls_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cls_name = str[start:end]
      _x = self
      start = end
      end += 4
      (_x.cls_id, _x.obj_id,) = _get_struct_2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H = None
def _get_struct_2H():
    global _struct_2H
    if _struct_2H is None:
        _struct_2H = struct.Struct("<2H")
    return _struct_2H
_struct_4Hf = None
def _get_struct_4Hf():
    global _struct_4Hf
    if _struct_4Hf is None:
        _struct_4Hf = struct.Struct("<4Hf")
    return _struct_4Hf
